#!/usr/bin/env bash
set -euo pipefail

REPO_URL="https://github.com/mlflow/mlflow"
BRANCH="master"
REPO_DIR="source-repo"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# --- Clone (skip if already exists) ---
if [ ! -d "$REPO_DIR" ]; then
    git clone --depth 1 --branch "$BRANCH" "$REPO_URL" "$REPO_DIR"
fi

cd "$REPO_DIR/docs"

# --- Node version ---
# package.json engines: node >=18.0, Docusaurus 3.x recommends Node 20+
node_major=$(node --version | cut -d. -f1 | tr -d 'v')
if [ "$node_major" -lt 18 ]; then
    echo "[ERROR] Node version $(node --version) does not satisfy >=18.0"
    exit 1
fi
echo "[INFO] Node $(node --version) OK"

# --- Package manager: npm (enforced via only-allow) ---
echo "[INFO] npm $(npm --version) OK"

# --- Dependencies ---
npm ci --ignore-scripts

# --- Apply fixes.json if present ---
FIXES_JSON="$SCRIPT_DIR/fixes.json"
if [ -f "$FIXES_JSON" ]; then
    echo "[INFO] Applying content fixes..."
    node -e "
    const fs = require('fs');
    const path = require('path');
    const fixes = JSON.parse(fs.readFileSync('$FIXES_JSON', 'utf8'));
    for (const [file, ops] of Object.entries(fixes.fixes || {})) {
        if (!fs.existsSync(file)) { console.log('  skip (not found):', file); continue; }
        let content = fs.readFileSync(file, 'utf8');
        for (const op of ops) {
            if (op.type === 'replace' && content.includes(op.find)) {
                content = content.split(op.find).join(op.replace || '');
                console.log('  fixed:', file, '-', op.comment || '');
            }
        }
        fs.writeFileSync(file, content);
    }
    for (const [file, cfg] of Object.entries(fixes.newFiles || {})) {
        const c = typeof cfg === 'string' ? cfg : cfg.content;
        fs.mkdirSync(path.dirname(file), {recursive: true});
        fs.writeFileSync(file, c);
        console.log('  created:', file);
    }
    "
fi

# --- Create stub files for missing notebook-derived docs ---
# Sidebars reference notebooks generated by the convert-notebooks script (requires Python/uv).
# Create stubs so Docusaurus can validate sidebars and run write-translations.

# GenAI docs stubs (sidebarsGenAI.ts, plugin id: genai, path: docs/genai)
GENAI_DOCS="docs/genai"
mkdir -p "$GENAI_DOCS/flavors/dspy/notebooks"
mkdir -p "$GENAI_DOCS/flavors/langchain/notebooks"
mkdir -p "$GENAI_DOCS/flavors/llama-index/notebooks"
mkdir -p "$GENAI_DOCS/flavors/custom-pyfunc-for-llms/notebooks"
mkdir -p "$GENAI_DOCS/flavors/chat-model-guide"
echo "# stub" > "$GENAI_DOCS/flavors/dspy/notebooks/dspy_quickstart-ipynb.md"
echo "# stub" > "$GENAI_DOCS/flavors/langchain/notebooks/langchain-quickstart-ipynb.md"
echo "# stub" > "$GENAI_DOCS/flavors/langchain/notebooks/langchain-retriever-ipynb.md"
echo "# stub" > "$GENAI_DOCS/flavors/llama-index/notebooks/llama_index_quickstart-ipynb.md"
echo "# stub" > "$GENAI_DOCS/flavors/llama-index/notebooks/llama_index_workflow_tutorial-ipynb.md"
echo "# stub" > "$GENAI_DOCS/flavors/custom-pyfunc-for-llms/notebooks/custom-pyfunc-advanced-llm-ipynb.md"
echo "# stub" > "$GENAI_DOCS/flavors/chat-model-guide/chat-model-tool-calling-ipynb.md"

# Classic ML docs stubs (sidebarsClassicML.ts, plugin id: classic-ml, path: docs/classic-ml)
CML_DOCS="docs/classic-ml"
mkdir -p "$CML_DOCS/traditional-ml/tutorials/hyperparameter-tuning/notebooks"
mkdir -p "$CML_DOCS/traditional-ml/tutorials/creating-custom-pyfunc/notebooks"
mkdir -p "$CML_DOCS/traditional-ml/tutorials/serving-multiple-models-with-pyfunc/notebooks"
mkdir -p "$CML_DOCS/deep-learning/transformers/tutorials/conversational"
mkdir -p "$CML_DOCS/deep-learning/transformers/tutorials/fine-tuning"
mkdir -p "$CML_DOCS/deep-learning/transformers/tutorials/audio-transcription"
mkdir -p "$CML_DOCS/deep-learning/transformers/tutorials/prompt-templating"
mkdir -p "$CML_DOCS/deep-learning/transformers/tutorials/text-generation"
mkdir -p "$CML_DOCS/deep-learning/transformers/tutorials/translation"
mkdir -p "$CML_DOCS/deep-learning/sentence-transformers/tutorials/quickstart"
mkdir -p "$CML_DOCS/deep-learning/sentence-transformers/tutorials/semantic-similarity"
mkdir -p "$CML_DOCS/deep-learning/sentence-transformers/tutorials/semantic-search"
mkdir -p "$CML_DOCS/deep-learning/sentence-transformers/tutorials/paraphrase-mining"
echo "# stub" > "$CML_DOCS/traditional-ml/tutorials/hyperparameter-tuning/notebooks/hyperparameter-tuning-with-child-runs-ipynb.md"
echo "# stub" > "$CML_DOCS/traditional-ml/tutorials/hyperparameter-tuning/notebooks/logging-plots-in-mlflow-ipynb.md"
echo "# stub" > "$CML_DOCS/traditional-ml/tutorials/hyperparameter-tuning/notebooks/parent-child-runs-ipynb.md"
echo "# stub" > "$CML_DOCS/traditional-ml/tutorials/creating-custom-pyfunc/notebooks/basic-pyfunc-ipynb.md"
echo "# stub" > "$CML_DOCS/traditional-ml/tutorials/creating-custom-pyfunc/notebooks/introduction-ipynb.md"
echo "# stub" > "$CML_DOCS/traditional-ml/tutorials/creating-custom-pyfunc/notebooks/override-predict-ipynb.md"
echo "# stub" > "$CML_DOCS/traditional-ml/tutorials/serving-multiple-models-with-pyfunc/notebooks/MME_Tutorial-ipynb.md"
echo "# stub" > "$CML_DOCS/deep-learning/transformers/tutorials/conversational/conversational-model-ipynb.md"
echo "# stub" > "$CML_DOCS/deep-learning/transformers/tutorials/conversational/pyfunc-chat-model-ipynb.md"
echo "# stub" > "$CML_DOCS/deep-learning/transformers/tutorials/fine-tuning/transformers-fine-tuning-ipynb.md"
echo "# stub" > "$CML_DOCS/deep-learning/transformers/tutorials/fine-tuning/transformers-peft-ipynb.md"
echo "# stub" > "$CML_DOCS/deep-learning/transformers/tutorials/audio-transcription/whisper-ipynb.md"
echo "# stub" > "$CML_DOCS/deep-learning/transformers/tutorials/prompt-templating/prompt-templating-ipynb.md"
echo "# stub" > "$CML_DOCS/deep-learning/transformers/tutorials/text-generation/text-generation-ipynb.md"
echo "# stub" > "$CML_DOCS/deep-learning/transformers/tutorials/translation/component-translation-ipynb.md"
echo "# stub" > "$CML_DOCS/deep-learning/sentence-transformers/tutorials/quickstart/sentence-transformers-quickstart-ipynb.md"
echo "# stub" > "$CML_DOCS/deep-learning/sentence-transformers/tutorials/semantic-similarity/semantic-similarity-sentence-transformers-ipynb.md"
echo "# stub" > "$CML_DOCS/deep-learning/sentence-transformers/tutorials/semantic-search/semantic-search-sentence-transformers-ipynb.md"
echo "# stub" > "$CML_DOCS/deep-learning/sentence-transformers/tutorials/paraphrase-mining/paraphrase-mining-sentence-transformers-ipynb.md"

# Additional stubs for redirect targets (without -ipynb suffix).
# docusaurus.config.ts has @docusaurus/plugin-client-redirects entries pointing FROM old paths
# TO these non-ipynb paths. The redirect targets must exist as actual pages.

# GenAI redirect targets
echo "# stub" > "$GENAI_DOCS/flavors/dspy/notebooks/dspy_quickstart.md"
echo "# stub" > "$GENAI_DOCS/flavors/langchain/notebooks/langchain-quickstart.md"
# langchain-retriever page has a cross-link to a specific section anchor in the source docs.
# Include the heading so the anchor exists in the stub and doesn't break the build.
printf -- '# stub\n\n## Establishing RetrievalQA Chain and Logging with MLflow\n' > "$GENAI_DOCS/flavors/langchain/notebooks/langchain-retriever.md"
echo "# stub" > "$GENAI_DOCS/flavors/llama-index/notebooks/llama_index_quickstart.md"
echo "# stub" > "$GENAI_DOCS/flavors/llama-index/notebooks/llama_index_workflow_tutorial.md"
echo "# stub" > "$GENAI_DOCS/flavors/custom-pyfunc-for-llms/notebooks/custom-pyfunc-advanced-llm.md"
echo "# stub" > "$GENAI_DOCS/flavors/chat-model-guide/chat-model-tool-calling.md"

# Classic ML redirect targets
mkdir -p "$CML_DOCS/model/notebooks"
echo "# stub" > "$CML_DOCS/model/notebooks/signature_examples.md"
# eval-monitor quickstart page links to this notebook page
mkdir -p "$GENAI_DOCS/eval-monitor/notebooks"
echo "# stub" > "$GENAI_DOCS/eval-monitor/notebooks/quickstart-eval.md"
echo "# stub" > "$CML_DOCS/traditional-ml/tutorials/creating-custom-pyfunc/notebooks/basic-pyfunc.md"
echo "# stub" > "$CML_DOCS/traditional-ml/tutorials/creating-custom-pyfunc/notebooks/introduction.md"
echo "# stub" > "$CML_DOCS/traditional-ml/tutorials/creating-custom-pyfunc/notebooks/override-predict.md"
echo "# stub" > "$CML_DOCS/traditional-ml/tutorials/hyperparameter-tuning/notebooks/hyperparameter-tuning-with-child-runs.md"
echo "# stub" > "$CML_DOCS/traditional-ml/tutorials/hyperparameter-tuning/notebooks/logging-plots-in-mlflow.md"
echo "# stub" > "$CML_DOCS/traditional-ml/tutorials/hyperparameter-tuning/notebooks/parent-child-runs.md"
echo "# stub" > "$CML_DOCS/traditional-ml/tutorials/serving-multiple-models-with-pyfunc/notebooks/MME_Tutorial.md"
echo "# stub" > "$CML_DOCS/deep-learning/transformers/tutorials/conversational/conversational-model.md"
echo "# stub" > "$CML_DOCS/deep-learning/transformers/tutorials/conversational/pyfunc-chat-model.md"
echo "# stub" > "$CML_DOCS/deep-learning/transformers/tutorials/fine-tuning/transformers-fine-tuning.md"
echo "# stub" > "$CML_DOCS/deep-learning/transformers/tutorials/fine-tuning/transformers-peft.md"
echo "# stub" > "$CML_DOCS/deep-learning/transformers/tutorials/audio-transcription/whisper.md"
# These two have the same name as their parent directory, which makes Docusaurus treat them
# as folder index pages (mapped to /prompt-templating/ and /text-generation/ respectively).
# Use a different filename with an explicit slug to create the correct /prompt-templating/prompt-templating
# and /text-generation/text-generation routes that the redirect targets expect.
printf -- '---\nslug: prompt-templating\n---\n# stub\n' > "$CML_DOCS/deep-learning/transformers/tutorials/prompt-templating/stub-content.md"
printf -- '---\nslug: text-generation\n---\n# stub\n' > "$CML_DOCS/deep-learning/transformers/tutorials/text-generation/stub-content.md"
echo "# stub" > "$CML_DOCS/deep-learning/transformers/tutorials/translation/component-translation.md"
echo "# stub" > "$CML_DOCS/deep-learning/sentence-transformers/tutorials/quickstart/sentence-transformers-quickstart.md"
echo "# stub" > "$CML_DOCS/deep-learning/sentence-transformers/tutorials/semantic-similarity/semantic-similarity-sentence-transformers.md"
echo "# stub" > "$CML_DOCS/deep-learning/sentence-transformers/tutorials/semantic-search/semantic-search-sentence-transformers.md"
echo "# stub" > "$CML_DOCS/deep-learning/sentence-transformers/tutorials/paraphrase-mining/paraphrase-mining-sentence-transformers.md"

echo "[DONE] Repository is ready for docusaurus commands."
